name: cycling_escape
description: A Cycling game by WiVe

version: 2.0.1+21

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  app_review: ^2.1.1+1
  audio_session: ^0.1.10
  auto_orientation: ^2.2.1
  collection: ^1.15.0
  device_info: ^2.0.3
  dio: ^4.0.0
  drift: ^1.1.0
  drift_db_viewer: ^1.0.0
  drift_inspector: ^1.0.0
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.4.3
  flame: ^1.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  get_it: ^7.2.0
  icapps_architecture: ^0.7.0
  injectable: ^1.4.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  just_audio: ^0.9.30
  niddler_dart: ^1.5.0
  package_info_plus: ^1.4.2 
  path: ^1.8.0
  path_provider: ^2.0.8
  plugin_platform_interface: ^2.1.2
  provider: ^6.0.0
  retrofit: ^3.0.0
  scroll_when_needed: ^2.0.0
  shared_preferences: ^2.0.11
  sqlite3_flutter_libs: ^0.5.2
  synchronized: ^3.0.0+2
  storage_inspector: ^0.1.1
  win32: ^2.6.1
  yaml: ^3.1.1
  url_launcher: ^6.1.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  icapps_license: ^2.0.0
  injectable_generator: ^1.5.0
  json_serializable: ^6.2.0
  mockito: ^5.0.15
  model_generator: ^5.8.1
  retrofit_generator: ^4.0.1
  locale_gen: ^4.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/cyclists/
    - assets/images/environment/
    - assets/fonts/
    - assets/icon/
    - assets/locale/
  fonts:
    - family: SaranaiGame
      fonts:
        - asset: assets/fonts/SaranaiGame-Bold.ttf

locale_gen:
  default_language: 'en'
  languages: ['en', 'nl', 'fr', 'es']
  locale_assets_path: 'assets/locale/'
  assets_path: 'assets/locale/'
  output_path: 'lib/util/locale/'

icapps_license:
  nullsafety: true
  licenses:
    device_info: 'https://raw.githubusercontent.com/flutter/plugins/master/packages/device_info/device_info/LICENSE'
    flutter_cache_manager: 'https://raw.githubusercontent.com/Baseflow/flutter_cache_manager/develop/flutter_cache_manager/LICENSE'

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true
